### ISSUE TITLE
An error occurred while running

### ISSUE THREAD

**Issue by 1-snail** [wzzheng/IDML#1]
When running image_retrieval/code/train.py it shows the error
An error is reported in the opt.step() line of code, showing
local variable 'beta1' referenced before assignment

**Comment by wzzheng** [comment]
Thanks for reporting this, we will look into it quickly.

**Comment by 1-snail** [comment]
The framework uses TripletLoss to report errors

**Comment by 1-snail** [comment]
The framework uses TripletLossto report errors

**Comment by wangck20** [comment]
> The framework uses TripletLossto report errors

Thanks for your question and attention. This code is for ProxyAnchor Loss with our method. The code for TripletLoss is on the way to being released.

**Comment by RainFrost1** [comment]
Any suggestions or solution for this error?

**Comment by wangck20** [comment]
> Any suggestions or solution for this error?
Thanks for your attention and sorry for the late reply! We applied our method on Triplet Loss using this baseline: https://github.com/Confusezius/Deep-Metric-Learning-Baselines. You could set another output in netlib.py to represent the uncertainty embedding. Then you could replace the original distance matrix with our introspective matrix in our paper (equation 6) in losses.py. Other settings are the same with the default code.

**Comment by wangck20** [comment]
> Any suggestions or solution for this error?

Thanks for your attention and sorry for the late reply. We applied our method on the Triplet Loss with the following baseline: https://github.com/zbr17/GeDML. In this baseline, you could set another output of the network to represent the uncertainty embedding in GeDML/src/gedml/core/models/basic_models/mlp.py. Then, you could replace the basic l_p distance metric with our introspective distance metric (equation 6 in our paper) in GeDML/src/gedml/core/metrics/distance_metrics/lp_metric.py. Other settings are the same with the default settings. Thank you again for your attention to our work!
