### ISSUE TITLE
May I ask what's the difference between your work and Proxy Synthesis?

### ISSUE THREAD

**Issue by Noahsark** [wzzheng/IDML#4]
Hi,
I think your work is promising and interesting. May I kindly ask what the difference is between your work and the Proxy Synthesis[1]? It seems you all try to search for a linear interpretation between different classes.

[1] Gu et al. "Proxy synthesis: Learning with synthetic classes for deep metric learning." AAAI 2021
github.com/navervision/proxy-synthesis

Thank you so much.

**Comment by wzzheng** [comment]
Hello, thanks for your interest!
Our work (IDML) focuses on an uncertainty-aware metric to cope with the uncertainty in training samples. This uncertainty may result from sample syntheses using mixup or using the AAAI paper you mentioned. Yet, IDML is more than this. We can also deal with other data augmentations or nothing at all (we have added relevant experiments and will update the paper in the future).
By the way, Proxy Synthesis is actually a follow-up of our previous paper Hardness-Aware Deep Metric Learning (CVPR 2019 oral & PAMI 2021, https://github.com/wzzheng/HDML), which is also worth reading :)
Feel free to ask if you have further questions regarding both works!
