### ISSUE TITLE
Question about tau and gamma.

### ISSUE THREAD

**Issue by minhquoc0712** [wzzheng/IDML#5]
Thank you for your interesting research.

I would be very happy if you can answer some of my questions:

1. You have this paragraph in your paper: 

"In addition, we fixed τ = 5 and set γ to 0, 1, 2, 3, 4 for training. The experimental results vary on the two datasets.
Specifically, our framework achieves the best performance when γ = 0 on the CUB-200-2011 dataset while γ = 3 on the Cars196 dataset. This indicates that the metric is more discreet when comparing images on the Cars196 dataset."

But on the left of figures 4. a and 4. b, we can see that the highest recall@1 corresponds to gamma = 2 for both CUB-200-2011 and Cars196 datasets. What is this different?

2. In your ProxyAnchor loss, you had set the gamma = 4, and tau = 5. Is this the set of hyperparameters you found has the highest performance on recall@1?

**Comment by wangck20** [comment]
Thanks for your interest.
1. We are sorry for this mistake. Figure 4 denotes the accurate results on both datasets. And we would revise the statement as "Specifically, our framework achieves the best performance when γ = 0 on the CUB-200-2011 dataset while γ = 2 on the Cars196 dataset". Thanks again for your nice comment.
2. This is not the set hyperparameters we found has the highest performance on recall@1. In figure 4, we demonstrate that the results would not be influenced much by the parameters so the settings of parameters are not strict.

**Comment by minhquoc0712** [comment]
Thank you for your response. It's clear to me now.
